# Generated by Django 3.2.2 on 2021-05-10 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('precio', models.FloatField(max_length=20)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='detalles_productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.FloatField(max_length=20)),
                ('valorTotal', models.FloatField(max_length=20)),
                ('valorIva', models.FloatField(max_length=20)),
                ('idProducto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prodcutos.productos')),
            ],
        ),
    ]
